### ISSUE TITLE
Double scroll bars on 'background' section

### ISSUE THREAD

**Issue by meisenheimere** [lavrton/polotno-studio#2]
![image](https://user-images.githubusercontent.com/16943019/100672550-56e84f00-331f-11eb-9c5f-5463457b61e6.png)

This is caused by the CSS rule of 'overflow:auto;' on the 'css-bisco' class.

Resolving this requires overflow-y to be set to **scroll** on the child element (the one with the images) and overflow-y on the parent container to be set to **hidden**. The scrollbar is also under the color panel content and you can fix that by setting a CSS calc style on the child to be the full height minus the section with the colors.

Example:

![image](https://user-images.githubusercontent.com/16943019/100673586-eb9f7c80-3320-11eb-9649-cd0c7e0dd7ee.png)

Result after fixes:

![image](https://user-images.githubusercontent.com/16943019/100673577-e8a48c00-3320-11eb-83ef-2034eb8e44f3.png)

**Comment by lavrton** [comment]
Thanks for the feedback. Should be fixed now.
