### ISSUE TITLE
Not able to save JSON

### ISSUE THREAD

**Issue by vinayakavajiraya** [lavrton/polotno-studio#5]
Hi,

Not able to save JSON by using the application via URL [https://studio.polotno.dev/](https://studio.polotno.dev/) on Edge browser on Windows 10.

Issue may have occurred within last 4-5 hours as I was able to save JSON before the time.

As there is no issue template, please let me know what are details are required for debuggingg the issue.

Thank you

**Comment by lavrton** [comment]
Hello. Thanks a lot for your report. I just pushed a fix. Please try it again and let me know if it works for you.

**Comment by vinayakavajiraya** [comment]
Hi @lavrton,

I confirm that issue is fixed. I am able to save JSON file.
Keep up the good work.

Thanks again!
